export const MESSAGE = {
  START_RECORDING: "START_RECORDING",
  STOP_RECORDING: "STOP_RECORDING",
  PAUSE_RECORDING: "PAUSE_RECORDING",
  RESUME_RECORDING: "RESUME_RECORDING",
  GET_STATUS: "GET_STATUS",
  RECORDING_STATUS: "RECORDING_STATUS",
  OFFSCREEN_START: "OFFSCREEN_START",
  OFFSCREEN_STOP: "OFFSCREEN_STOP",
  OFFSCREEN_PAUSE: "OFFSCREEN_PAUSE",
  OFFSCREEN_RESUME: "OFFSCREEN_RESUME",
  OFFSCREEN_STARTED: "OFFSCREEN_STARTED",
  OFFSCREEN_STOPPED: "OFFSCREEN_STOPPED",
  OFFSCREEN_CHUNK: "OFFSCREEN_CHUNK",
  OFFSCREEN_ERROR: "OFFSCREEN_ERROR",
  OFFSCREEN_EVENT: "OFFSCREEN_EVENT",
  CONTENT_EVENT: "CONTENT_EVENT",
  INJECT_CONTROLLER: "INJECT_CONTROLLER",
  SESSION_READY: "SESSION_READY",
  SETTINGS_UPDATE: "SETTINGS_UPDATE",
  SETTINGS_GET: "SETTINGS_GET"
};

export const DB_NAME = "cinematic_recorder";
export const DB_VERSION = 1;

export const STORE = {
  SESSIONS: "sessions",
  CHUNKS: "chunks",
  EVENTS: "events",
  SETTINGS: "settings",
  LOGS: "logs"
};

export const SESSION_STATE = {
  IDLE: "idle",
  RECORDING: "recording",
  PAUSED: "paused",
  PROCESSING: "processing",
  READY: "ready",
  ERROR: "error"
};

export const DEFAULT_SETTINGS = {
  withMic: false,
  withTabAudio: true,
  resolution: "1080p",
  fps: 30,
  qualityPreset: "balanced",
  easingPreset: "medium"
};
